#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias pipi="devpi install "
alias pipe="pip install -e"
alias pipu='pip uninstall'
alias rgrep='grep -r'
alias hd='hexdump -C'
alias gp='git pull && git push'

function _save_cd {
  cd $@
  rm -f ~/.cwd
  echo $PWD > ~/.cwd
}
[[ -e ~/.cwd ]] && cd `cat ~/.cwd`
alias cd=_save_cd

source $HOME/.profile
source $HOME/.rcpriv

# Mac Key Bindings
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
