#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias pipi="pip install -U "
alias pipe="pip install -e"
alias pipu='pip uninstall'

source $HOME/.profile

[[ "`uname`" == "Linux" ]] && source /local/tc/bin/activate_gti

export PIP_INDEX_URL="http://devpi-eu.dolby.net/ngc/prod"
export PIP_TRUSTED_HOST="devpi-eu.dolby.net devpi-au.dolby.net devpi.dolby.net"

