#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias pipi="devpi install "
alias pipe="pip install -e"
alias pipu='pip uninstall'
alias rgrep='grep -r'
alias hd='hexdump -C'
alias gp='git pull && git push'

source $HOME/.profile

[[ "`uname`" == "Linux" ]] && source /local/tc/bin/activate_gti

# Mac Key Bindings
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word

